# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [3]:
import numpy as np

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
arr = np.random.randint(0, 21, (4,7))
arr

array([[17,  2,  1, 16,  1,  4,  5],
       [ 1,  4, 17, 19,  8,  5, 15],
       [11, 20, 14, 13,  2,  2,  6],
       [ 9,  1,  8,  2,  1, 11,  2]])

In [5]:
arr/20

array([[0.85, 0.1 , 0.05, 0.8 , 0.05, 0.2 , 0.25],
       [0.05, 0.2 , 0.85, 0.95, 0.4 , 0.25, 0.75],
       [0.55, 1.  , 0.7 , 0.65, 0.1 , 0.1 , 0.3 ],
       [0.45, 0.05, 0.4 , 0.1 , 0.05, 0.55, 0.1 ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [6]:
arr2 = np.random.randint(0, 11, (8,10))
sm = [i.sum() for i in arr2]
print(arr2[sm.index(min(sm))])
print('индекс строки с минимальной суммой = {}'.format(sm.index(min(sm))))

[2 7 1 0 4 6 0 3 3 8]
индекс строки с минимальной суммой = 0


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [7]:
a = np.random.randint(1, 6, 4)
b = np.random.randint(1, 6, 4)
evkl = np.linalg.norm(a - b)
print(a, b, evkl, end = ' ')

# np.linalg.norm() - функция для нахождения евклидова расстояния 

[4 3 1 1] [2 2 5 4] 5.477225575051661 

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [8]:
A = np.array([[-1,2,4], [-3,1,2], [-3,0,1]])
B = np.array([[3,-1], [2,1]])
C = np.array([[7,21], [11,8], [8,4]])
X = np.linalg.inv(A) @ (-C) @ np.linalg.inv(B)
X

# np.linalg.inv() - функция для нахождения обратной матрицы

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [9]:
recipes = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
recipes[:5]

# loadtxt(fname, dtype=float, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, quotechar=None,like=None)

#    1. fname (обязательный) - имя файла или файлоподобный объект, из которого нужно загрузить данные.
#    2. dtype (опциональный) - тип данных, в который нужно преобразовать загруженные значения.
#    3. comments (опциональный) - символ комментария, все строки, начинающиеся с этого символа, будут проигнорированы.
#    4. delimiter (опциональный) - разделитель между значениями в файле.
#    5. skiprows (опциональный) - количество строк, которые нужно пропустить перед началом загрузки данных.
#    6. usecols (опциональный) - индексы столбцов, которые нужно загрузить.
#    7. unpack (опциональный) - если True, данные будут распакованы в отдельные массивы столбцов.
#    8. ndmin (опциональный) - минимальное количество измерений, которое должны иметь загруженные данные.

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

In [10]:
# альтернативный вариант
import csv
with open('minutes_n_ingredients.csv') as f:
    f1 = csv.reader(f, delimiter=',')
    header = next(f1)
    rows = np.array([r for r in f1], dtype=np.int32)
print(' '.join(header)) 
print(rows[:4])

id minutes n_ingredients
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [11]:
minutes_average_value = np.average(recipes[:,1])
minutes_min = np.min(recipes[:,1])
minutes_max = np.max(recipes[:,1])
minutes_median = np.median(recipes[:,1])
print('Среднее значение для минут = ', minutes_average_value)
print('Минимальное значение для минут = ', minutes_min)
print('Максимальное значение для минут = ', minutes_max)
print('Медиана для минут = ', minutes_median)

Среднее значение для минут =  21601.00169
Минимальное значение для минут =  0
Максимальное значение для минут =  2147483647
Медиана для минут =  40.0


In [12]:
ingredients_average_value = np.average(recipes[:,2])
ingredients_min = np.min(recipes[:,1])
ingredients_max = np.max(recipes[:,1])
ingredients_median = np.median(recipes[:,1])
print('Среднее значение для ингредиентов = ', ingredients_average_value)
print('Минимальное значение для ингредиентов = ', ingredients_min)
print('Максимальное значение для ингредиентов = ', ingredients_max)
print('Медиана для ингредиентов = ', ingredients_median)

Среднее значение для ингредиентов =  9.05528
Минимальное значение для ингредиентов =  0
Максимальное значение для ингредиентов =  2147483647
Медиана для ингредиентов =  40.0


In [13]:
# np.average() - Среднее значение
# np.min() - Минимальное значение
# np.max() - Максимальное значение
# np.median() - Медиана

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [14]:
print(recipes[:,1:2].max())
minutes = recipes[:,1:2]
block = np.clip(minutes, 0, np.quantile(minutes, 0.75))
print(block)
print(block.max())

# np.clip(a, a_min, a_max) - ограничение значений массива в определенном диапазоне
#    1. a (обязательный) - массив, значения которого нужно ограничить.
#    2. a_min (обязательный) - минимальное значение, которое может принимать массив. Если элемент массива меньше a_min, он будет заменен на a_min.
#    3. a_max (обязательный) - максимальное значение, которое может принимать массив. Если элемент массива больше a_max, он будет заменен на a_max.

# np.quantile(a, q, axis=None)
#    1. a (обязательный) - массив, для которого нужно вычислить квантиль.
#    2. q (обязательный) - значение квантиля, которое должно быть в диапазоне от 0 до 1. Например, 0.5 соответствует медиане.
#    3. axis (необязательный) - ось, по которой нужно вычислить квантиль. Если не указано, квантиль вычисляется по всему массиву.

2147483647
[[60.]
 [25.]
 [10.]
 ...
 [65.]
 [ 5.]
 [65.]]
65.0


In [15]:
# альтернативный вариант с изменением самого файла 
time = sorted(list(set(rows[:, 1])))
time_q = [i if i <= time[int(len(time)*0.75)] else time[int(len(time)*0.75)] for i in rows[:, 1]]

import csv
# Открываем исходный CSV файл и создаем временный файл для записи данных с замененным столбцом
with open('minutes_n_ingredients.csv', 'r') as csvfile, open('NEW_minutes_n_ingredients.csv', 'w', newline='') as newcsvfile:
    reader = csv.reader(csvfile)
    writer = csv.writer(newcsvfile)
    
    # Указываем индекс столбца, который нужно заменить и данные для нового столбца
    column_to_replace = 1  
    new_column_data = time_q # данные для нового столбца
    
    for i, row in enumerate(reader):
        if i == 0:  # Если это первая строка (заголовок), заменяем название столбца
            row[column_to_replace] = 'minutes'
        else:
            row[column_to_replace] = new_column_data[i - 1]  # Заменяем данные в указанном столбце
        
        writer.writerow(row)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [16]:
print(len(recipes[:,1:2][recipes[:,1:2] == 0]))
recipes[:,1:2][recipes[:,1:2] == 0] = 1
print(len(recipes[:,1:2][recipes[:,1:2] == 0]))

479
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [17]:
uniq_recipes = np.unique(recipes, axis=0)
len(uniq_recipes)

# np.unique(arr, axis=None)
#    arr - многомерный массив
#    axis - указывает, по какой оси нужно искать уникальные значения
#        В случае двумерного массива (матрицы), ось 0 соответствует строкам, а ось 1 соответствует столбцам.

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [18]:
uniq_ingredients = np.unique(recipes[:,2])
len(uniq_ingredients), uniq_ingredients

(37,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39], dtype=int32))

In [19]:
# образец приминения 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [1, 2, 3]])
uniq_recipes1 = np.unique(matrix, axis=0) # по строкам
uniq_recipes2 = np.unique(matrix, axis=1) # по столбцам
uniq_recipes3 = np.unique(matrix) # по всем значениям
uniq_recipes4 = np.unique(matrix[:,2]) # по значениям из одного столбца
len(uniq_recipes1), len(uniq_recipes2), len(uniq_recipes3), len(uniq_recipes4)

(2, 3, 6, 2)

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [20]:
recipes_with_no_more_5ing = recipes[recipes[:,2] <= 5]
print(recipes_with_no_more_5ing, len(recipes_with_no_more_5ing), end=' ')

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]] 17262 

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [29]:
ing_for_min = np.array([])
for e in range(recipes.shape[0]):
    ing_for_min = np.append(ing_for_min, recipes[:,2][e]/recipes[:,1:2][e])
ing_for_min, ing_for_min.max()

(array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
        0.1       ]),
 24.0)

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [34]:
top100_rec = np.argsort(recipes[:,1:2])[:100:-1] # индексы рецептов с наибольшей продолжительностью 
ingr = np.array([])
for i in top100_rec:
    ingr = np.append(ingr, recipes[:,2][i])
np.average(ingr)

# np.argsort() - возвращает индексы элементов массива в отсортированном порядке

16.0

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [35]:
random_recipes = np.random.randint(0, recipes.shape[0], 10)
print(recipes[random_recipes])

[[ 81859      5      6]
 [367704     20      6]
 [285773     35      9]
 [225770     60      9]
 [217653     55     13]
 [ 21667     25      9]
 [514034     60     13]
 [407060     30      7]
 [448258    200     13]
 [312767     30      4]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [41]:
aver_ing = np.average(recipes[:,2])
no_more_aver = recipes[:,2][recipes[:,2] < aver_ing]
len(no_more_aver)/len(recipes)*100

58.802

In [60]:
# альтернативный вариант
(recipes[recipes[:, 2] < np.mean(recipes[:, 2])].shape[0] / recipes.shape[0]) * 100

# np.mean() - вычисление среднего значения элементов в массиве

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [54]:
simple_rec = np.array([])
for m in recipes[:,1:2]<=20:
    for i in recipes[:,2]<=5:
        if m and i:
            np.append(simple_rec, 1)
        else:
            np.append(simple_rec, 0)
new_recipes = recipes + simple_rec
new_recipes, new_recipes.shape

KeyboardInterrupt: 

In [63]:
simple_rec2 = np.array((recipes[:, 1] <= 20) & (recipes[:, 2] <= 5)).reshape(-1,1).astype('int')
new_recipes2 = np.concatenate((recipes, simple_rec2), axis=1)
new_recipes2

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

In [64]:
# arr.reshape(-1,1) - столбец
# arr.reshape(1,-1) - строка

13. Выведите процент "простых" рецептов в датасете

In [66]:
(simple_rec2[simple_rec2 == 1].shape[0] / simple_rec2.shape[0]) * 100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [67]:
# 1 - короткие (менее 10)
# 2 - средние (более 10, но менее 20)
# 3 - длинные (более 20)